
development:
  adapter: postgresql
  encoding: unicode
  database: compartilhe_dev
  pool: 5
  username: compartilhe
  password: compartilhe
  host: localhost
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: compartilhe_test
  pool: 5
  username: compartilhe
  password: compartilhe
  host: localhost
  port: 5433
production:
  adapter: postgresql
  encoding: unicode
  database: compartilhe_production
  pool: 5
  username: compartilhe
  password:
